<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Molecules\Molecule\MoleculeFactory\MoleculeFactory.csproj" />
    <ProjectReference Include="..\Molecules\Molecule\MoleculeRepository\MoleculeRepository.csproj" />
    <ProjectReference Include="..\Molecules\Molecule\MoleculeServices\MoleculeServices.csproj" />
    <ProjectReference Include="..\Molecules\Process\MoleculeProcessFactory\MoleculeProcessFactory.csproj" />
    <ProjectReference Include="..\Molecules\Process\MoleculeProcessService\MoleculeProcessService.csproj" />
    <ProjectReference Include="..\Molecules\ResearchDefinition\ResearchDefinitionRepository\ResearchDefinitionRepository.csproj" />
    <ProjectReference Include="..\Molecules\ResearchDefinition\ResearchDefinitionService\ResearchDefinitionService.csproj" />
    <ProjectReference Include="..\Utilities\UtilitiesServices\UtilitiesServices.csproj" />
  </ItemGroup>

</Project>
